#!/bin/bash

# Available environment variables: https://docs.docker.com/docker-cloud/builds/advanced/#environment-variables-for-building-and-testing

docker build --build-arg VCS_REF=`git rev-parse --short HEAD` \
  --build-arg VCS_URL="https://github.com/greenkeeper-keeper/reference-instance" \
  --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
  --build-arg NODE_VERSION=`cat ./.nvmrc` \
  --build-arg VERSION=${DOCKER_TAG} \
  -t $IMAGE_NAME .
